# Copyright 2019 the Tectonic Project
# Licensed under the MIT License.

# Triggered when a pull request is issued against the master branch that
# modifies files in the "cross-images" subdirectory. Does a test build of the
# Docker images.

trigger:
  branches:
    exclude:
    - '*'

pr:
  branches:
    include:
    - master
  paths:
    include:
    - cross-images/

variables:
- template: variables.yml

jobs:
- job: build_builders
  pool:
    vmImage: ${{ variables.linux_image }}

  strategy:
    matrix:
      ${{ each vpair in variables }}:
        ${{ if startsWith(vpair.key, 'target_') }}:
          ${{ vpair.key }}:
            target_id: ${{ vpair.key }}
            target_kabob: ${{ vpair.value }}

  steps:
  - template: build-builder-steps.yml
    parameters:
      platform: $(target_kabob)
