# Copyright 2019 the Tectonic Project
# Licensed under the MIT License.

parameters:
- name: cross_tag
  type: string

steps:
- script: |
    docker build -t tectonictypesetting/ttcross:${{ parameters.cross_tag }} custom-cross/
    docker tag tectonictypesetting/ttcross:${{ parameters.cross_tag }} tectonictypesetting/ttcross:latest
  displayName: Build ttcross Docker image (tag ${{ parameters.cross_tag }})
