# Copyright 2019 the Tectonic Project
# Licensed under the MIT License.

# Steps to build the helper tool on Linux.

parameters:
- name: rustup_toolchain
  type: string

steps:
- script: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
    echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
  displayName: Install Rust (non-Windows)
  condition: ne(variables['Agent.OS'], 'Windows_NT')
- script: |
    curl -sSf -o rustup-init.exe https://win.rustup.rs
    rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN%
    echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
  displayName: Install Rust (Windows)
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
- script: |
    cd tool
    cargo test --release --all
  displayName: Build and test ttcitool
