# Copyright 2019 the Tectonic Project
# Licensed under the MIT License.

jobs:

- job: cross_builder_${{ parameters.platform_uscore }}
  pool:
    vmImage: 'ubuntu-18.04'

  steps:
    - script: |
        cd cross-images
        ./build.${{ parameters.platform }}.sh
      displayName: Build crossbuild:${{ parameters.platform }} Docker image

    - task: Docker@2
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
      displayName: Push image to Hub
      inputs:
        containerRegistry: |
          pkgw@DockerHub
        repository: tectonictypesetting/crossbuilder
        tags: |
          ${{ parameters.platform }}
          latest
