# Copyright 2019 the Tectonic Project
# Licensed under the MIT License.

jobs:

- job: custom_cross
  pool:
    vmImage: 'ubuntu-18.04'

  steps:
    - displayName: Build ttcross Docker image
      script: |
        docker build -t tectonictypesetting/ttcross:${{ parameters.tag }} custom-cross/
        docker tag tectonictypesetting/ttcross:${{ parameters.tag }} tectonictypesetting/ttcross:latest

    - task: Docker@2
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
      displayName: Push image to Hub
      inputs:
        containerRegistry: |
          pkgw@DockerHub
        repository: ttcross
        tags: |
          ${{ parameters.tag }}
          latest
